version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "⬆️ ci"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "⬆️ chore"
    groups:
      composer-dev:
        dependency-type: "development"
